version: '3.8'
networks:
  mdm-observ:

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - mdm-observ

  ws1-exporter:
    container_name: ws1-exporter
    # Default latest tag for testing only, in PROD use a specific stable version
    image: ghcr.io/christopherime/ws1-exporter:latest
    environment:
      - WS1_AUTH_KEY=${WS1_AUTH_KEY}
      - WS1_TENANT_KEY=${WS1_TENANT_KEY}
      - WS1_URL=${WS1_URL}
      - WS1_EXPORTER_PORT=${WS1_EXPORTER_PORT}
      - WS1_TENANT_NAME=${WS1_TENANT_NAME}
      - WS1_INTERVAL=${WS1_INTERVAL}
    # host : container, 8080 arbitraly chosen, might change it later for a 9xxx port as most common for prom. exporter
    ports:
      - 8080:8080
    networks:
      - mdm-observ
