global:
  scrape_interval: 5m
  scrape_timeout: 10s
scrape_configs:
- job_name: 'ws1-exporter'
  static_configs: 
    - targets: ['ws1-exporter:8080']
      labels:
        instance: 'ws1'
        job: 'ws1-exporter'
