apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ws1-exporter.fullname" . }}
  labels:
    {{- include "ws1-exporter.labels" . | nindent 4 }}
stringData:
    ws1AuthKey: {{ .Values.ws1AuthKey}}
    ws1TenantKey: {{ .Values.ws1TenantKey}}
    ws1Url: {{ .Values.ws1Url}}
    ws1TenantName: {{ .Values.ws1TenantName}}
    ws1Interval: {{ .Values.ws1Interval}}
